<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="/assets/js/extjs-3.4.1.1/resources/css/ext-all.css" />
    <script src="/assets/js/extjs-3.4.1.1/adapter/ext/ext-base.js" type="text/javascript"></script>
    <script src="/assets/js/extjs-3.4.1.1/ext-all-debug.js" type="text/javascript"></script>
<!--    <script src="/assets/js/extjs-3.4.1.1/ext-all.js" type="text/javascript"></script>-->
    <script type="text/javascript" src="/assets/js/test/test.js"></script>
    <script type="text/javascript" src="/assets/js/test/components/other.js"></script>
    <script type="text/javascript" src="/assets/js/test/misc/utils.js"></script>
    <script type="text/javascript" src="/assets/js/test/components/window.js"></script>
    <script type="text/javascript" src="/assets/js/test/widgets/users.windows.js"></script>
    <script type="text/javascript" src="/assets/js/test/components/grid.js"></script>
    <script type="text/javascript" src="/assets/js/test/widgets/users.grid.js"></script>
    <script type="text/javascript" src="/assets/js/test/widgets/qualification.grid.js"></script>
  <script type="text/javascript" src="/assets/js/test/sections/home.js"></script>

</head>
<body>
<script type="text/javascript">
//    Ext.onReady(function() {
//        Ext.add({ xtype: "test-page-home"});
//    });
Ext.onReady(function() {

//console.log('isRegistered', Ext.ComponentMgr.isRegistered("my-panel") );
//    Ext.ComponentMgr.create({xtype: "my-panel"});
//    Ext.ComponentMgr.create({xtype: "test-page-home"});
    Ext.ComponentMgr.create({xtype: "test-panel-home"});
});

</script>
<?php //echo $this->content ?>
<?php //echo $this->page ?>
<div style="margin: auto;width: 80%"  id="test"></div>
</body>
</html>